version: '3.0'

networks:
  codenation:
    driver: bridge

services:
  codenation:
    build:
      context: ./
      dockerfile: Dockerfile
    image: codenation
    restart: always
    env_file: .env
    ports:
      - "6606:6606"
    networks:
      - codenation
  codenation_postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=codenation
      - POSTGRES_PASSWORD=codenationpassword
      - POSTGRES_DB=codenation_db
    ports:
      - "5432:5432"
    networks:
      - codenation